### ISSUE TITLE
upper => Lower case

### ISSUE THREAD

**Issue by Hoedic** [opennorth/ovc-vdm#10]
See with @jpmckinney to lower case

**Comment by jpmckinney** [comment]
We just need a French word list/dictionary to apply my algorithm. For English, I use the Scrabble word list: https://code.google.com/p/scrabblehelper/source/browse/#svn%2Ftrunk%2FScrabbleHelper%2Fsrc%2Fdictionaries

**Comment by jpmckinney** [comment]
https://raw.githubusercontent.com/gaultier/CaesarDecryption/master/dico.txt seems good

**Comment by jpmckinney** [comment]
https://github.com/jpmckinney/indoor_voice#readme
